name: Main
on:
  push:
    branches:
      - master
  pull_request:
    types:
      - opened
      - synchronize
jobs:
  tests:
    name: Tests
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2
      - name: Setup Ruby
        uses: ruby/setup-ruby@v1
        with:
          bundler-cache: true
      - name: Run tests
        run: bin/rspec
      - name: Cache code coverage reports
        uses: actions/cache@v2
        with:
          path: |
            coverage/.last_run.json
            coverage/.resultset.json
          key: ${{ runner.os }}-simplecov-report-${{ github.ref }}
  coverage:
    name: Coverage
    needs: tests
    runs-on: ubuntu-latest
    steps:
      - name: Get cached code coverage reports
        uses: actions/cache@v2
        with:
          path: |
            coverage/.last_run.json
            coverage/.resultset.json
          key: ${{ runner.os }}-simplecov-report-${{ github.ref }}
      - name: Get head cached code coverage reports
        uses: actions/cache@v2
        with:
          path: |
            coverage-head/.last_run.json
            coverage-head/.resultset.json
          key: ${{ runner.os }}-simplecov-report-${{ github.head_ref }}
      - name: Ruby Simplecov Report
        uses: D1ceWard/ruby-simplecov-action@master
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
