name: Main
on:
  push:
    branches:
      - master
  pull_request:
    types:
      - opened
      - synchronize
jobs:
  tests:
    name: Tests
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2
      - name: Setup Ruby
        uses: ruby/setup-ruby@v1
        with:
          bundler-cache: true
      - name: Run tests
        run: bin/rspec
      - name: Upload Code Coverage artifact
        uses: actions/upload-artifact@v2
        with:
          name: code-coverage
          path: coverage/
  coverage:
    name: Coverage
    needs: tests
    runs-on: ubuntu-latest
    steps:
      - name: Download Code Coverage artifact
        uses: actions/download-artifact@v2
        with:
          name: code-coverage
          path: coverage/
      - name: Ruby Simplecov Report
        uses: D1ceWard/ruby-simplecov-action@master
